//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administra
    {
        public int IdAdministra { get; set; }
        public int IdUsuario { get; set; }
        public int IdSitio { get; set; }
    
        public virtual Sitios Sitios { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
