//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProyectoBAEntities2 : DbContext
    {
        public ProyectoBAEntities2()
            : base("name=ProyectoBAEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administra> Administra { get; set; }
        public virtual DbSet<Establecimientos> Establecimientos { get; set; }
        public virtual DbSet<Fotos> Fotos { get; set; }
        public virtual DbSet<membresia> membresia { get; set; }
        public virtual DbSet<Recibo> Recibo { get; set; }
        public virtual DbSet<Sitios> Sitios { get; set; }
        public virtual DbSet<tarjetaCredito> tarjetaCredito { get; set; }
        public virtual DbSet<TipoEstablecimiento> TipoEstablecimiento { get; set; }
        public virtual DbSet<TipoPago> TipoPago { get; set; }
        public virtual DbSet<ubicaciones> ubicaciones { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<VISTARECIBO> VISTARECIBO { get; set; }
    
        public virtual int AgregarADMINISTRA(Nullable<int> iDUSUARIO, Nullable<int> iDSITIO)
        {
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarADMINISTRA", iDUSUARIOParameter, iDSITIOParameter);
        }
    
        public virtual int AgregarESTABLECIMIENTOS(string nOMBRE, Nullable<int> iDTIPOESTABLECIMIENTO)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iDTIPOESTABLECIMIENTOParameter = iDTIPOESTABLECIMIENTO.HasValue ?
                new ObjectParameter("IDTIPOESTABLECIMIENTO", iDTIPOESTABLECIMIENTO) :
                new ObjectParameter("IDTIPOESTABLECIMIENTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarESTABLECIMIENTOS", nOMBREParameter, iDTIPOESTABLECIMIENTOParameter);
        }
    
        public virtual int AgregarFOTOS(string fOTO, Nullable<int> iDSITIO)
        {
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(string));
    
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarFOTOS", fOTOParameter, iDSITIOParameter);
        }
    
        public virtual int AgregarMEMBRESIA(string nOMBREMEMBRESIA, Nullable<int> dURACIONMESES, Nullable<decimal> cOSTO, Nullable<int> nUMSITIOS)
        {
            var nOMBREMEMBRESIAParameter = nOMBREMEMBRESIA != null ?
                new ObjectParameter("NOMBREMEMBRESIA", nOMBREMEMBRESIA) :
                new ObjectParameter("NOMBREMEMBRESIA", typeof(string));
    
            var dURACIONMESESParameter = dURACIONMESES.HasValue ?
                new ObjectParameter("DURACIONMESES", dURACIONMESES) :
                new ObjectParameter("DURACIONMESES", typeof(int));
    
            var cOSTOParameter = cOSTO.HasValue ?
                new ObjectParameter("COSTO", cOSTO) :
                new ObjectParameter("COSTO", typeof(decimal));
    
            var nUMSITIOSParameter = nUMSITIOS.HasValue ?
                new ObjectParameter("NUMSITIOS", nUMSITIOS) :
                new ObjectParameter("NUMSITIOS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarMEMBRESIA", nOMBREMEMBRESIAParameter, dURACIONMESESParameter, cOSTOParameter, nUMSITIOSParameter);
        }
    
        public virtual int AgregarRECIBO(Nullable<System.DateTime> fECHA, Nullable<int> iDUSUARIO, Nullable<int> iDMEMBRESIA, Nullable<int> iDTIPOPAGO)
        {
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            var iDMEMBRESIAParameter = iDMEMBRESIA.HasValue ?
                new ObjectParameter("IDMEMBRESIA", iDMEMBRESIA) :
                new ObjectParameter("IDMEMBRESIA", typeof(int));
    
            var iDTIPOPAGOParameter = iDTIPOPAGO.HasValue ?
                new ObjectParameter("IDTIPOPAGO", iDTIPOPAGO) :
                new ObjectParameter("IDTIPOPAGO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarRECIBO", fECHAParameter, iDUSUARIOParameter, iDMEMBRESIAParameter, iDTIPOPAGOParameter);
        }
    
        public virtual int AgregarSITIOS(string dESCRIPCION, string nOMBRE, Nullable<int> iDESTABLECIMIENTO)
        {
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iDESTABLECIMIENTOParameter = iDESTABLECIMIENTO.HasValue ?
                new ObjectParameter("IDESTABLECIMIENTO", iDESTABLECIMIENTO) :
                new ObjectParameter("IDESTABLECIMIENTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarSITIOS", dESCRIPCIONParameter, nOMBREParameter, iDESTABLECIMIENTOParameter);
        }
    
        public virtual int AgregarTARJETACREDITO(string nUMTARJETA, string cVV, string mES, string aNIO, Nullable<int> iDUSUARIO)
        {
            var nUMTARJETAParameter = nUMTARJETA != null ?
                new ObjectParameter("NUMTARJETA", nUMTARJETA) :
                new ObjectParameter("NUMTARJETA", typeof(string));
    
            var cVVParameter = cVV != null ?
                new ObjectParameter("CVV", cVV) :
                new ObjectParameter("CVV", typeof(string));
    
            var mESParameter = mES != null ?
                new ObjectParameter("MES", mES) :
                new ObjectParameter("MES", typeof(string));
    
            var aNIOParameter = aNIO != null ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(string));
    
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarTARJETACREDITO", nUMTARJETAParameter, cVVParameter, mESParameter, aNIOParameter, iDUSUARIOParameter);
        }
    
        public virtual int AgregarTipoEstablecimiento(string nombreTipo)
        {
            var nombreTipoParameter = nombreTipo != null ?
                new ObjectParameter("NombreTipo", nombreTipo) :
                new ObjectParameter("NombreTipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarTipoEstablecimiento", nombreTipoParameter);
        }
    
        public virtual int AgregarTIPOPAGO(string nOMBRE)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarTIPOPAGO", nOMBREParameter);
        }
    
        public virtual int AgregarUBICACIONES(string dIRECCION, string lATITUD, string lONGITUD, Nullable<int> iDSITIO)
        {
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var lATITUDParameter = lATITUD != null ?
                new ObjectParameter("LATITUD", lATITUD) :
                new ObjectParameter("LATITUD", typeof(string));
    
            var lONGITUDParameter = lONGITUD != null ?
                new ObjectParameter("LONGITUD", lONGITUD) :
                new ObjectParameter("LONGITUD", typeof(string));
    
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarUBICACIONES", dIRECCIONParameter, lATITUDParameter, lONGITUDParameter, iDSITIOParameter);
        }
    
        public virtual int AgregarUSUARIO(string nOMBRE, string aPELLIDOS, string cONTRASENA, string uSUARIO)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOSParameter = aPELLIDOS != null ?
                new ObjectParameter("APELLIDOS", aPELLIDOS) :
                new ObjectParameter("APELLIDOS", typeof(string));
    
            var cONTRASENAParameter = cONTRASENA != null ?
                new ObjectParameter("CONTRASENA", cONTRASENA) :
                new ObjectParameter("CONTRASENA", typeof(string));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarUSUARIO", nOMBREParameter, aPELLIDOSParameter, cONTRASENAParameter, uSUARIOParameter);
        }
    
        public virtual ObjectResult<DevolverTablaADMINISTRA_Result> DevolverTablaADMINISTRA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DevolverTablaADMINISTRA_Result>("DevolverTablaADMINISTRA");
        }
    
        public virtual ObjectResult<DevolverTablaESTABLECIMIENTOS_Result> DevolverTablaESTABLECIMIENTOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DevolverTablaESTABLECIMIENTOS_Result>("DevolverTablaESTABLECIMIENTOS");
        }
    
        public virtual ObjectResult<DevolverTablaFOTOS_Result> DevolverTablaFOTOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DevolverTablaFOTOS_Result>("DevolverTablaFOTOS");
        }
    
        public virtual ObjectResult<DevolverTablaMEMBRESIA_Result> DevolverTablaMEMBRESIA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DevolverTablaMEMBRESIA_Result>("DevolverTablaMEMBRESIA");
        }
    
        public virtual ObjectResult<DevolverTablaRECIBO_Result> DevolverTablaRECIBO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DevolverTablaRECIBO_Result>("DevolverTablaRECIBO");
        }
    
        public virtual ObjectResult<DevolverTablaSITIOS_Result> DevolverTablaSITIOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DevolverTablaSITIOS_Result>("DevolverTablaSITIOS");
        }
    
        public virtual ObjectResult<DevolverTablaTARJETACREDITO_Result> DevolverTablaTARJETACREDITO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DevolverTablaTARJETACREDITO_Result>("DevolverTablaTARJETACREDITO");
        }
    
        public virtual ObjectResult<DevolverTablaTipoEstablecimiento_Result> DevolverTablaTipoEstablecimiento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DevolverTablaTipoEstablecimiento_Result>("DevolverTablaTipoEstablecimiento");
        }
    
        public virtual ObjectResult<DevolverTablaTIPOPAGO_Result> DevolverTablaTIPOPAGO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DevolverTablaTIPOPAGO_Result>("DevolverTablaTIPOPAGO");
        }
    
        public virtual ObjectResult<DevolverTablaUSUARIO_Result> DevolverTablaUSUARIO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DevolverTablaUSUARIO_Result>("DevolverTablaUSUARIO");
        }
    
        public virtual int EliminarADMINISTRA(Nullable<int> iDADMINISTRA)
        {
            var iDADMINISTRAParameter = iDADMINISTRA.HasValue ?
                new ObjectParameter("IDADMINISTRA", iDADMINISTRA) :
                new ObjectParameter("IDADMINISTRA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarADMINISTRA", iDADMINISTRAParameter);
        }
    
        public virtual int EliminarESTABLECIMIENTOS(Nullable<int> iDESTABLECIMIENTO)
        {
            var iDESTABLECIMIENTOParameter = iDESTABLECIMIENTO.HasValue ?
                new ObjectParameter("IDESTABLECIMIENTO", iDESTABLECIMIENTO) :
                new ObjectParameter("IDESTABLECIMIENTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarESTABLECIMIENTOS", iDESTABLECIMIENTOParameter);
        }
    
        public virtual int EliminarFOTOS(Nullable<int> iDFOTO)
        {
            var iDFOTOParameter = iDFOTO.HasValue ?
                new ObjectParameter("IDFOTO", iDFOTO) :
                new ObjectParameter("IDFOTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarFOTOS", iDFOTOParameter);
        }
    
        public virtual int EliminarMEMBRESIA(Nullable<int> iDMEMBRESIA)
        {
            var iDMEMBRESIAParameter = iDMEMBRESIA.HasValue ?
                new ObjectParameter("IDMEMBRESIA", iDMEMBRESIA) :
                new ObjectParameter("IDMEMBRESIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarMEMBRESIA", iDMEMBRESIAParameter);
        }
    
        public virtual int EliminarRECIBO(Nullable<int> iDRECIBO)
        {
            var iDRECIBOParameter = iDRECIBO.HasValue ?
                new ObjectParameter("IDRECIBO", iDRECIBO) :
                new ObjectParameter("IDRECIBO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarRECIBO", iDRECIBOParameter);
        }
    
        public virtual int EliminarSITIOS(Nullable<int> iDSITIO)
        {
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarSITIOS", iDSITIOParameter);
        }
    
        public virtual int EliminarTARJETACREDITO(Nullable<int> iDTARJETA)
        {
            var iDTARJETAParameter = iDTARJETA.HasValue ?
                new ObjectParameter("IDTARJETA", iDTARJETA) :
                new ObjectParameter("IDTARJETA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarTARJETACREDITO", iDTARJETAParameter);
        }
    
        public virtual int EliminarTipoEstablecimiento(Nullable<int> idTipoEstablecimiento)
        {
            var idTipoEstablecimientoParameter = idTipoEstablecimiento.HasValue ?
                new ObjectParameter("IdTipoEstablecimiento", idTipoEstablecimiento) :
                new ObjectParameter("IdTipoEstablecimiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarTipoEstablecimiento", idTipoEstablecimientoParameter);
        }
    
        public virtual int EliminarTIPOPAGO(Nullable<int> iDTIPOPAGO)
        {
            var iDTIPOPAGOParameter = iDTIPOPAGO.HasValue ?
                new ObjectParameter("IDTIPOPAGO", iDTIPOPAGO) :
                new ObjectParameter("IDTIPOPAGO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarTIPOPAGO", iDTIPOPAGOParameter);
        }
    
        public virtual int EliminarUBICACIONES(Nullable<int> uBICACION)
        {
            var uBICACIONParameter = uBICACION.HasValue ?
                new ObjectParameter("UBICACION", uBICACION) :
                new ObjectParameter("UBICACION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarUBICACIONES", uBICACIONParameter);
        }
    
        public virtual int EliminarUSUARIO(Nullable<int> iDUSUARIO)
        {
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarUSUARIO", iDUSUARIOParameter);
        }
    
        public virtual int FiltrarADMINISTRA(Nullable<int> iDADMINISTRA, Nullable<int> iDUSUARIO, Nullable<int> iDSITIO)
        {
            var iDADMINISTRAParameter = iDADMINISTRA.HasValue ?
                new ObjectParameter("IDADMINISTRA", iDADMINISTRA) :
                new ObjectParameter("IDADMINISTRA", typeof(int));
    
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FiltrarADMINISTRA", iDADMINISTRAParameter, iDUSUARIOParameter, iDSITIOParameter);
        }
    
        public virtual int FiltrarESTABLECIMIENTOS(Nullable<int> iDESTABLECIMIENTO, string nOMBRE, Nullable<int> iDTIPOESTABLECIMIENTO)
        {
            var iDESTABLECIMIENTOParameter = iDESTABLECIMIENTO.HasValue ?
                new ObjectParameter("IDESTABLECIMIENTO", iDESTABLECIMIENTO) :
                new ObjectParameter("IDESTABLECIMIENTO", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iDTIPOESTABLECIMIENTOParameter = iDTIPOESTABLECIMIENTO.HasValue ?
                new ObjectParameter("IDTIPOESTABLECIMIENTO", iDTIPOESTABLECIMIENTO) :
                new ObjectParameter("IDTIPOESTABLECIMIENTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FiltrarESTABLECIMIENTOS", iDESTABLECIMIENTOParameter, nOMBREParameter, iDTIPOESTABLECIMIENTOParameter);
        }
    
        public virtual int FiltrarFOTOS(Nullable<int> iDFOTO, string fOTO, Nullable<int> iDSITIO)
        {
            var iDFOTOParameter = iDFOTO.HasValue ?
                new ObjectParameter("IDFOTO", iDFOTO) :
                new ObjectParameter("IDFOTO", typeof(int));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(string));
    
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FiltrarFOTOS", iDFOTOParameter, fOTOParameter, iDSITIOParameter);
        }
    
        public virtual int FiltrarMEMBRESIA(Nullable<int> iDMEMBRESIA, string nOMBREMEMBRESIA, Nullable<int> dURACIONMESES, Nullable<decimal> cOSTO, Nullable<int> nUMSITIOS)
        {
            var iDMEMBRESIAParameter = iDMEMBRESIA.HasValue ?
                new ObjectParameter("IDMEMBRESIA", iDMEMBRESIA) :
                new ObjectParameter("IDMEMBRESIA", typeof(int));
    
            var nOMBREMEMBRESIAParameter = nOMBREMEMBRESIA != null ?
                new ObjectParameter("NOMBREMEMBRESIA", nOMBREMEMBRESIA) :
                new ObjectParameter("NOMBREMEMBRESIA", typeof(string));
    
            var dURACIONMESESParameter = dURACIONMESES.HasValue ?
                new ObjectParameter("DURACIONMESES", dURACIONMESES) :
                new ObjectParameter("DURACIONMESES", typeof(int));
    
            var cOSTOParameter = cOSTO.HasValue ?
                new ObjectParameter("COSTO", cOSTO) :
                new ObjectParameter("COSTO", typeof(decimal));
    
            var nUMSITIOSParameter = nUMSITIOS.HasValue ?
                new ObjectParameter("NUMSITIOS", nUMSITIOS) :
                new ObjectParameter("NUMSITIOS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FiltrarMEMBRESIA", iDMEMBRESIAParameter, nOMBREMEMBRESIAParameter, dURACIONMESESParameter, cOSTOParameter, nUMSITIOSParameter);
        }
    
        public virtual int FiltrarRECIBO(Nullable<int> iDRECIBO, Nullable<System.DateTime> fECHA, Nullable<int> iDUSUARIO, Nullable<int> iDMEMBRESIA, Nullable<int> iDTIPOPAGO)
        {
            var iDRECIBOParameter = iDRECIBO.HasValue ?
                new ObjectParameter("IDRECIBO", iDRECIBO) :
                new ObjectParameter("IDRECIBO", typeof(int));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            var iDMEMBRESIAParameter = iDMEMBRESIA.HasValue ?
                new ObjectParameter("IDMEMBRESIA", iDMEMBRESIA) :
                new ObjectParameter("IDMEMBRESIA", typeof(int));
    
            var iDTIPOPAGOParameter = iDTIPOPAGO.HasValue ?
                new ObjectParameter("IDTIPOPAGO", iDTIPOPAGO) :
                new ObjectParameter("IDTIPOPAGO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FiltrarRECIBO", iDRECIBOParameter, fECHAParameter, iDUSUARIOParameter, iDMEMBRESIAParameter, iDTIPOPAGOParameter);
        }
    
        public virtual int FiltrarSITIOS(Nullable<int> iDSITIO, string dESCRIPCION, string nOMBRE, Nullable<int> iDESTABLECIMIENTO)
        {
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iDESTABLECIMIENTOParameter = iDESTABLECIMIENTO.HasValue ?
                new ObjectParameter("IDESTABLECIMIENTO", iDESTABLECIMIENTO) :
                new ObjectParameter("IDESTABLECIMIENTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FiltrarSITIOS", iDSITIOParameter, dESCRIPCIONParameter, nOMBREParameter, iDESTABLECIMIENTOParameter);
        }
    
        public virtual int FiltrarTARJETACREDITO(Nullable<int> iDTARJETA, string nUMTARJETA, string cVV, string mES, string aNIO)
        {
            var iDTARJETAParameter = iDTARJETA.HasValue ?
                new ObjectParameter("IDTARJETA", iDTARJETA) :
                new ObjectParameter("IDTARJETA", typeof(int));
    
            var nUMTARJETAParameter = nUMTARJETA != null ?
                new ObjectParameter("NUMTARJETA", nUMTARJETA) :
                new ObjectParameter("NUMTARJETA", typeof(string));
    
            var cVVParameter = cVV != null ?
                new ObjectParameter("CVV", cVV) :
                new ObjectParameter("CVV", typeof(string));
    
            var mESParameter = mES != null ?
                new ObjectParameter("MES", mES) :
                new ObjectParameter("MES", typeof(string));
    
            var aNIOParameter = aNIO != null ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FiltrarTARJETACREDITO", iDTARJETAParameter, nUMTARJETAParameter, cVVParameter, mESParameter, aNIOParameter);
        }
    
        public virtual int FiltrarTipoEstablecimiento(Nullable<int> idTipoEstablecimiento, string nombreTipo)
        {
            var idTipoEstablecimientoParameter = idTipoEstablecimiento.HasValue ?
                new ObjectParameter("IdTipoEstablecimiento", idTipoEstablecimiento) :
                new ObjectParameter("IdTipoEstablecimiento", typeof(int));
    
            var nombreTipoParameter = nombreTipo != null ?
                new ObjectParameter("NombreTipo", nombreTipo) :
                new ObjectParameter("NombreTipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FiltrarTipoEstablecimiento", idTipoEstablecimientoParameter, nombreTipoParameter);
        }
    
        public virtual int FiltrarTIPOPAGO(Nullable<int> iDTIPOPAGO, string nOMBRE)
        {
            var iDTIPOPAGOParameter = iDTIPOPAGO.HasValue ?
                new ObjectParameter("IDTIPOPAGO", iDTIPOPAGO) :
                new ObjectParameter("IDTIPOPAGO", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FiltrarTIPOPAGO", iDTIPOPAGOParameter, nOMBREParameter);
        }
    
        public virtual int FiltrarUBICACIONES(Nullable<int> uBICACION, string dIRECCION, string lATITUD, string lONGITUD, Nullable<int> iDSITIO)
        {
            var uBICACIONParameter = uBICACION.HasValue ?
                new ObjectParameter("UBICACION", uBICACION) :
                new ObjectParameter("UBICACION", typeof(int));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var lATITUDParameter = lATITUD != null ?
                new ObjectParameter("LATITUD", lATITUD) :
                new ObjectParameter("LATITUD", typeof(string));
    
            var lONGITUDParameter = lONGITUD != null ?
                new ObjectParameter("LONGITUD", lONGITUD) :
                new ObjectParameter("LONGITUD", typeof(string));
    
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FiltrarUBICACIONES", uBICACIONParameter, dIRECCIONParameter, lATITUDParameter, lONGITUDParameter, iDSITIOParameter);
        }
    
        public virtual int FiltrarUSUARIO(Nullable<int> iDUSUARIO, string nOMBRE, string aPELLIDOS, string cONTRASENA, string uSUARIO)
        {
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOSParameter = aPELLIDOS != null ?
                new ObjectParameter("APELLIDOS", aPELLIDOS) :
                new ObjectParameter("APELLIDOS", typeof(string));
    
            var cONTRASENAParameter = cONTRASENA != null ?
                new ObjectParameter("CONTRASENA", cONTRASENA) :
                new ObjectParameter("CONTRASENA", typeof(string));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FiltrarUSUARIO", iDUSUARIOParameter, nOMBREParameter, aPELLIDOSParameter, cONTRASENAParameter, uSUARIOParameter);
        }
    
        public virtual int ModifcarADMINISTRA(Nullable<int> iDADMINISTRA, Nullable<int> iDUSUARIO, Nullable<int> iDSITIO)
        {
            var iDADMINISTRAParameter = iDADMINISTRA.HasValue ?
                new ObjectParameter("IDADMINISTRA", iDADMINISTRA) :
                new ObjectParameter("IDADMINISTRA", typeof(int));
    
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifcarADMINISTRA", iDADMINISTRAParameter, iDUSUARIOParameter, iDSITIOParameter);
        }
    
        public virtual int ModifcarESTABLECIMIENTOS(Nullable<int> iDESTABLECIMIENTO, string nOMBRE, Nullable<int> iDTIPOESTABLECIMIENTO)
        {
            var iDESTABLECIMIENTOParameter = iDESTABLECIMIENTO.HasValue ?
                new ObjectParameter("IDESTABLECIMIENTO", iDESTABLECIMIENTO) :
                new ObjectParameter("IDESTABLECIMIENTO", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iDTIPOESTABLECIMIENTOParameter = iDTIPOESTABLECIMIENTO.HasValue ?
                new ObjectParameter("IDTIPOESTABLECIMIENTO", iDTIPOESTABLECIMIENTO) :
                new ObjectParameter("IDTIPOESTABLECIMIENTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifcarESTABLECIMIENTOS", iDESTABLECIMIENTOParameter, nOMBREParameter, iDTIPOESTABLECIMIENTOParameter);
        }
    
        public virtual int ModifcarFOTOS(Nullable<int> iDFOTO, string fOTO, Nullable<int> iDSITIO)
        {
            var iDFOTOParameter = iDFOTO.HasValue ?
                new ObjectParameter("IDFOTO", iDFOTO) :
                new ObjectParameter("IDFOTO", typeof(int));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(string));
    
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifcarFOTOS", iDFOTOParameter, fOTOParameter, iDSITIOParameter);
        }
    
        public virtual int ModifcarMEMBRESIA(Nullable<int> iDMEMBRESIA, string nOMBREMEMBRESIA, Nullable<int> dURACIONMESES, Nullable<decimal> cOSTO, Nullable<int> nUMSITIOS)
        {
            var iDMEMBRESIAParameter = iDMEMBRESIA.HasValue ?
                new ObjectParameter("IDMEMBRESIA", iDMEMBRESIA) :
                new ObjectParameter("IDMEMBRESIA", typeof(int));
    
            var nOMBREMEMBRESIAParameter = nOMBREMEMBRESIA != null ?
                new ObjectParameter("NOMBREMEMBRESIA", nOMBREMEMBRESIA) :
                new ObjectParameter("NOMBREMEMBRESIA", typeof(string));
    
            var dURACIONMESESParameter = dURACIONMESES.HasValue ?
                new ObjectParameter("DURACIONMESES", dURACIONMESES) :
                new ObjectParameter("DURACIONMESES", typeof(int));
    
            var cOSTOParameter = cOSTO.HasValue ?
                new ObjectParameter("COSTO", cOSTO) :
                new ObjectParameter("COSTO", typeof(decimal));
    
            var nUMSITIOSParameter = nUMSITIOS.HasValue ?
                new ObjectParameter("NUMSITIOS", nUMSITIOS) :
                new ObjectParameter("NUMSITIOS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifcarMEMBRESIA", iDMEMBRESIAParameter, nOMBREMEMBRESIAParameter, dURACIONMESESParameter, cOSTOParameter, nUMSITIOSParameter);
        }
    
        public virtual int ModifcarRECIBO(Nullable<int> iDRECIBO, Nullable<System.DateTime> fECHA, Nullable<int> iDUSUARIO, Nullable<int> iDMEMBRESIA, Nullable<int> iDTIPOPAGO)
        {
            var iDRECIBOParameter = iDRECIBO.HasValue ?
                new ObjectParameter("IDRECIBO", iDRECIBO) :
                new ObjectParameter("IDRECIBO", typeof(int));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            var iDMEMBRESIAParameter = iDMEMBRESIA.HasValue ?
                new ObjectParameter("IDMEMBRESIA", iDMEMBRESIA) :
                new ObjectParameter("IDMEMBRESIA", typeof(int));
    
            var iDTIPOPAGOParameter = iDTIPOPAGO.HasValue ?
                new ObjectParameter("IDTIPOPAGO", iDTIPOPAGO) :
                new ObjectParameter("IDTIPOPAGO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifcarRECIBO", iDRECIBOParameter, fECHAParameter, iDUSUARIOParameter, iDMEMBRESIAParameter, iDTIPOPAGOParameter);
        }
    
        public virtual int ModifcarSITIOS(Nullable<int> iDSITIO, string dESCRIPCION, string nOMBRE, Nullable<int> iDESTABLECIMIENTO)
        {
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iDESTABLECIMIENTOParameter = iDESTABLECIMIENTO.HasValue ?
                new ObjectParameter("IDESTABLECIMIENTO", iDESTABLECIMIENTO) :
                new ObjectParameter("IDESTABLECIMIENTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifcarSITIOS", iDSITIOParameter, dESCRIPCIONParameter, nOMBREParameter, iDESTABLECIMIENTOParameter);
        }
    
        public virtual int ModifcarTARJETACREDITO(Nullable<int> iDTARJETA, string nUMTARJETA, string cVV, string mES, string aNIO, Nullable<int> iDUSUARIO)
        {
            var iDTARJETAParameter = iDTARJETA.HasValue ?
                new ObjectParameter("IDTARJETA", iDTARJETA) :
                new ObjectParameter("IDTARJETA", typeof(int));
    
            var nUMTARJETAParameter = nUMTARJETA != null ?
                new ObjectParameter("NUMTARJETA", nUMTARJETA) :
                new ObjectParameter("NUMTARJETA", typeof(string));
    
            var cVVParameter = cVV != null ?
                new ObjectParameter("CVV", cVV) :
                new ObjectParameter("CVV", typeof(string));
    
            var mESParameter = mES != null ?
                new ObjectParameter("MES", mES) :
                new ObjectParameter("MES", typeof(string));
    
            var aNIOParameter = aNIO != null ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(string));
    
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifcarTARJETACREDITO", iDTARJETAParameter, nUMTARJETAParameter, cVVParameter, mESParameter, aNIOParameter, iDUSUARIOParameter);
        }
    
        public virtual int ModifcarTipoEstablecimiento(Nullable<int> idTipoEstablecimiento, string nombreTipo)
        {
            var idTipoEstablecimientoParameter = idTipoEstablecimiento.HasValue ?
                new ObjectParameter("IdTipoEstablecimiento", idTipoEstablecimiento) :
                new ObjectParameter("IdTipoEstablecimiento", typeof(int));
    
            var nombreTipoParameter = nombreTipo != null ?
                new ObjectParameter("NombreTipo", nombreTipo) :
                new ObjectParameter("NombreTipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifcarTipoEstablecimiento", idTipoEstablecimientoParameter, nombreTipoParameter);
        }
    
        public virtual int ModifcarTIPOPAGO(Nullable<int> iDTIPOPAGO, string nOMBRE)
        {
            var iDTIPOPAGOParameter = iDTIPOPAGO.HasValue ?
                new ObjectParameter("IDTIPOPAGO", iDTIPOPAGO) :
                new ObjectParameter("IDTIPOPAGO", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifcarTIPOPAGO", iDTIPOPAGOParameter, nOMBREParameter);
        }
    
        public virtual int ModifcarUBICACIONES(Nullable<int> iDUBICACION, string dIRECCION, string lATITUD, string lONGITUD, Nullable<int> iDSITIO)
        {
            var iDUBICACIONParameter = iDUBICACION.HasValue ?
                new ObjectParameter("IDUBICACION", iDUBICACION) :
                new ObjectParameter("IDUBICACION", typeof(int));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var lATITUDParameter = lATITUD != null ?
                new ObjectParameter("LATITUD", lATITUD) :
                new ObjectParameter("LATITUD", typeof(string));
    
            var lONGITUDParameter = lONGITUD != null ?
                new ObjectParameter("LONGITUD", lONGITUD) :
                new ObjectParameter("LONGITUD", typeof(string));
    
            var iDSITIOParameter = iDSITIO.HasValue ?
                new ObjectParameter("IDSITIO", iDSITIO) :
                new ObjectParameter("IDSITIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifcarUBICACIONES", iDUBICACIONParameter, dIRECCIONParameter, lATITUDParameter, lONGITUDParameter, iDSITIOParameter);
        }
    
        public virtual int ModifcarUSUARIO(Nullable<int> iDUSUARIO, string nOMBRE, string aPELLIDOS, string cONTRASENA, string uSUARIO)
        {
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOSParameter = aPELLIDOS != null ?
                new ObjectParameter("APELLIDOS", aPELLIDOS) :
                new ObjectParameter("APELLIDOS", typeof(string));
    
            var cONTRASENAParameter = cONTRASENA != null ?
                new ObjectParameter("CONTRASENA", cONTRASENA) :
                new ObjectParameter("CONTRASENA", typeof(string));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifcarUSUARIO", iDUSUARIOParameter, nOMBREParameter, aPELLIDOSParameter, cONTRASENAParameter, uSUARIOParameter);
        }
    }
}
