//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicaciones
    {
        public int IdUbicacion { get; set; }
        public string Direccion { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public int IdSitio { get; set; }
    
        public virtual Sitios Sitios { get; set; }
    }
}
