//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public int IdRecibo { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public int IdTipoPago { get; set; }
        public int IdMembresia { get; set; }
    
        public virtual membresia membresia { get; set; }
        public virtual TipoPago TipoPago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
