//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjetaCredito
    {
        public int IdTarjeta { get; set; }
        public string NumTarjeta { get; set; }
        public string cvv { get; set; }
        public string anio { get; set; }
        public string mes { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
