//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTARECIBO
    {
        public int Clave { get; set; }
        public System.DateTime fecha { get; set; }
        public string Membresia { get; set; }
        public int Idmembresia { get; set; }
        public int Duracion { get; set; }
        public decimal Costo { get; set; }
        public int numeroSitios { get; set; }
        public int TipoPago { get; set; }
        public Nullable<int> idUsuario { get; set; }
    }
}
